services:
  # database section
  honeywell_video_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: honeywell_video_db
    environment:
      SA_PASSWORD: 'Passw0rd!'
      ACCEPT_EULA: 'Y'
    volumes:
      - honeywell_sqlserver_data:/var/opt/mssql
    restart: always
    ports:
      - '1433:1433'

volumes:
  honeywell_sqlserver_data:
    external: false
